SyntaxError: EOL while scanning string literal
[flake8](http://flake8.pycqa.org) testing of https://github.com/pallets/flask-website on Python 3.8.0

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./flask_website/database.py:96:26: F821 undefined name 'unicode'
                    body=unicode(self.rendered_body),
                         ^
./flask_website/database.py:104:16: F821 undefined name 'unicode'
            id=unicode(self.id),
               ^
./flask_website/database.py:150:26: F821 undefined name 'unicode'
                    text=unicode(self.rendered_text))
                         ^
./flask_website/search.py:34:33: F821 undefined name 'unicode'
        writer.add_document(url=unicode(self.url),
                                ^
./flask_website/search.py:51:38: F821 undefined name 'unicode'
        writer.delete_by_term('url', unicode(self.url))
                                     ^
./flask_website/search.py:93:22: F821 undefined name 'unicode'
        q = qp.parse(unicode(query))
                     ^
./flask_website/docs.py:30:16: F821 undefined name 'unicode'
            id=unicode(self.slug),
               ^
./flask_website/listings/extensions.py:694:58: E999 SyntaxError: EOL while scanning string literal
    Extension('Flask-MailboxValidator', 'MailboxValidator,
                                                         ^
./flask_website/listings/projects.py:25:29: F821 undefined name 'unicode'
        rv['description'] = unicode(rv['description'])
                            ^
1     E999 SyntaxError: EOL while scanning string literal
8     F821 undefined name 'unicode'
9
```
__E9,F63,F7,F82__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. They are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree